#!/bin/bash

set -eo pipefail

[[ -r /etc/default/solr ]] && source /etc/default/solr
default_core_path="${SOLR_HOME}/../default-collection"
new_core_name=$1; shift

if [[ ! -d $default_core_path ]]
then
  echo "Couldn't find the default core directory at '${default_core_path}'"
  exit 1
fi

new_core_path="${SOLR_HOME}/solr/${new_core_name}"

if [[ -d $new_core_path ]]; then
  echo "Core '${new_core_name}' already exists"
  exit 0
fi

cp -r "$default_core_path" "$new_core_path"
echo "name=${1}" > "${new_core_path}/core.properties"
chown -R ${SOLR_USER}:${SOLR_GROUP} "$new_core_path"
