software_groups: &software
  - "base"
jobs:
  solr:
    builder: "make"
    base: "ubuntu:12.04"
    software_groups: *software
    packages:
      - type: debian
        name: solr
        version: 4.8.1-5
        depends:
          - openjdk-7-jre-headless
          - runit-common
        target: install
        repos:
          - mxm-public
        activates:
          - solr-upgrade
